#FROM jupyter/scipy-notebook:2d878db5cbff
#FROM jupyter/minimal-notebook:latest
FROM jupyterhub/singleuser:latest

COPY ./conda/requirements.txt /home/jovyan/requirements.txt
COPY ./conda/.condarc /home/jovyan/.condarc
ENV CONDARC=/home/jovyan/.condarc
RUN conda install -n root --file /home/jovyan/requirements.txt \
    && conda update --all -n root
# ENV CONDARC=
# RUN rm /home/jovyan/requirements.txt
# RUN rm /home/jovyan/.condarc

